baseURL = "https://vib5252.github.io/tor-visualization/"
languageCode = "en-us"
title = "TOR Visualization"
theme = "mostafa-hugo-theme"
publishDir = "docs"
relativeURLs = true
canonifyURLs = true

[module]
  [[module.imports]]
    path = "github.com/mirmousaviii/mostafa-hugo-theme"


[params]
  author = "Vaibhav Chhabra"
  description = "Interactive visualization of Tor relays using unsupervised learning and trust scoring"
  showMenu = false
  contentTypeName = "index"
  mainSections = ["posts"]
  showReadingTime = false
  showDate = false
  enableSearch = false
  defaultTheme = "dark"
  textColor = "#adadadff"                   # Lighter normal text
  headerTextColor = "#c7e97dff"             # Yellow-orange for headers
  articleBackgroundColor = "#212733"      # Dark blue-gray for cards
  navBackgroundColor = "#151a1e"          # Even darker nav
  highlightColor = "#c7e97dff"              # Teal accent
  metaTextColor = "#a8d56eff"               # Lighter meta
  footerBackgroundColor = "#191d23"       # Footer
  footerHeadlineColor = "#a8d56eff"     # prominent text (sometimes not used for copyright)