baseURL = "https://vib5252.github.io/tor-visualization/"
languageCode = "en-us"
title = "TOR Project"
theme = "hugo-xterm"
publishDir = "docs"
relativeURLs = true
canonifyURLs = true

[params]
  author = "Vaibhav Chhabra"
  description = "Interactive visualization of Tor relays using unsupervised learning and trust scoring"
  showMenu = false
  contentTypeName = "index"
  mainSections = ["."]
  showReadingTime = false
  showDate = false
  enableSearch = false
