baseURL = "https://vib5252.github.io/tor-visualization/"
languageCode = "en-us"
title = "TOR Project"
theme = "PaperMod"
publishDir = "docs"
relativeURLs = true
canonifyURLs = true

[params]
  author = "Vaibhav Chhabra"
  description = "Interactive visualization of Tor relays using unsupervised learning and trust scoring"
  ShowReadingTime = true
  defaultTheme = "dark"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2
