name = 'Mostafa Hugo Theme'
license = 'MIT'
licenselink = 'https://github.com/mirmousaviii/mostafa-hugo-theme/blob/main/LICENSE'
description = 'A responsive theme with supports multilingual and various content types.'
homepage = 'https://github.com/mirmousaviii/mostafa-hugo-theme'
demosite = 'https://mirmousaviii.github.io/mostafa-hugo-theme/'
tags = [
    'blog',
    'responsive',
    'minimal',
    'multilingual',
    'personal',
    'dark',
    'dark-mode',
    'gallery',
    'podcast',
    'video'
]
features = [
    'multilingual',
    'content-types',
    'responsive',
    'single-column',
    'blog',
    'media',
    'cover-image',
    'archive',
    'social-icons',
    'minified-assets',
    'scroll-to-top'
]
min_version = "0.125.7"

[author]
  name = 'Mostafa Mirmousavi'
  homepage = 'https://mirmousavi.com/'
